version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: python manage.py runserver localhost:8000

    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=proj_owner
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=projement
