version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=proj_owner
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=projement
  web:
    build: .
    ports:
      - "8000:8000"
    command: python projement/manage.py runserver 0.0.0.0:8000

    depends_on:
      - db
    volumes:
    - .:/src

