version: '3'
services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=proj_owner
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=projement
    volumes:
      - .:/src
  web:
    build: .
    ports:
      - "8080:8080"
    command: bash entrypoint.sh

    depends_on:
      - db
    volumes:
    - .:/src

