# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Project title')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Project start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Project end date')),
                ('estimated_design', models.PositiveSmallIntegerField(verbose_name='Estimated design hours')),
                ('actual_design', models.PositiveSmallIntegerField(default=0, verbose_name='Actual design hours')),
                ('estimated_development', models.PositiveSmallIntegerField(verbose_name='Estimated development hours')),
                ('actual_development', models.PositiveSmallIntegerField(default=0, verbose_name='Actual development hours')),
                ('estimated_testing', models.PositiveSmallIntegerField(verbose_name='Estimated testing hours')),
                ('actual_testing', models.PositiveSmallIntegerField(default=0, verbose_name='Actual testing hours')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.Company')),
            ],
        ),
    ]
