# Generated by Django 2.2 on 2019-12-03 13:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Project title')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Project start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Project end date')),
                ('estimated_design', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(0)], verbose_name='Estimated design hours')),
                ('actual_design', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(0)], verbose_name='Actual design hours')),
                ('estimated_development', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(0)], verbose_name='Estimated development hours')),
                ('actual_development', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(0)], verbose_name='Actual development hours')),
                ('estimated_testing', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(0)], verbose_name='Estimated testing hours')),
                ('actual_testing', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(0)], verbose_name='Actual testing hours')),
                ('additional_hour_design', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(0)])),
                ('additional_hour_development', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(0)])),
                ('additional_hour_testing', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(0)])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.Company')),
                ('tags', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryOfChanges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_actual_design', models.CharField(blank=True, max_length=164)),
                ('actual_development', models.CharField(blank=True, max_length=164)),
                ('actual_testing', models.CharField(blank=True, max_length=164)),
                ('change_time', models.TimeField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='DataOfTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=240)),
                ('time_to_add', models.TimeField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
