# Generated by Django 2.2 on 2019-12-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='_change',
            field=models.IntegerField(default=0),
        ),
    ]
