# Generated by Django 2.2 on 2019-12-02 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20191202_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='actual_design',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Actual design hours'),
        ),
        migrations.AlterField(
            model_name='project',
            name='actual_development',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Actual development hours'),
        ),
        migrations.AlterField(
            model_name='project',
            name='actual_testing',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Actual testing hours'),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_design',
            field=models.PositiveSmallIntegerField(verbose_name='Estimated design hours'),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_development',
            field=models.PositiveSmallIntegerField(verbose_name='Estimated development hours'),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_testing',
            field=models.PositiveSmallIntegerField(verbose_name='Estimated testing hours'),
        ),
    ]
