# Generated by Django 2.2 on 2019-12-10 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project__change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='_change',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_published',
        ),
    ]
