# Generated by Django 2.2 on 2019-12-10 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20191210_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='additional_hour_design',
        ),
        migrations.RemoveField(
            model_name='project',
            name='additional_hour_development',
        ),
        migrations.RemoveField(
            model_name='project',
            name='additional_hour_testing',
        ),
    ]
