# Generated by Django 2.2 on 2019-12-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20191204_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='project', to='projects.Tag'),
        ),
    ]
