# Generated by Django 2.2 on 2019-12-04 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20191204_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='additional_hour_design',
        ),
        migrations.RemoveField(
            model_name='project',
            name='additional_hour_development',
        ),
        migrations.RemoveField(
            model_name='project',
            name='additional_hour_testing',
        ),
    ]
