# Generated by Django 2.0 on 2019-12-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20191212_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initialdataofproject',
            name='initial_actual_design',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='initialdataofproject',
            name='initial_actual_development',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='initialdataofproject',
            name='initial_actual_testing',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
