# Generated by Django 2.2 on 2019-12-05 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20191205_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyofchanges',
            name='additional_hour_design',
        ),
        migrations.RemoveField(
            model_name='historyofchanges',
            name='additional_hour_development',
        ),
        migrations.RemoveField(
            model_name='historyofchanges',
            name='additional_hour_testing',
        ),
    ]
