# Generated by Django 2.0 on 2019-12-27 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20191213_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.Company'),
        ),
    ]
